import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Use | Reused",
    description: "Read the terms and conditions governing your use of the Reused.in platform.",
};

export default function TermsPage() {
    return (
        <>
            <Header />
            <main className="container mx-auto px-4 py-8 max-w-4xl">
                <h1 className="text-2xl md:text-3xl font-bold mb-6 text-[#0a2e5e]">Terms of Use</h1>

                <div className="bg-white p-8 rounded-lg shadow-sm prose prose-blue max-w-none">
                    <p className="mb-4">
                        This document is an electronic record under the Information Technology Act, 2000. It is generated by a computer system and does not require any digital or physical signatures.
                    </p>
                    <p className="mb-4">
                        This Terms of Use document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. It governs your use of the website reused.in (&quot;Platform&quot;), including the mobile site and mobile application.
                    </p>
                    <p className="mb-6">
                        The Platform is owned by Reused.in, with its registered office at Karnataka, India. By using the Platform, you agree to these Terms of Use.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">1. General Terms</h2>
                    <ul className="list-disc ml-6 mb-4 space-y-1">
                        <li>You agree to provide accurate and complete information when registering or using the Platform.</li>
                        <li>You are responsible for all activities carried out under your account.</li>
                        <li>Unauthorized use of the Platform may give rise to damages and/or criminal liability.</li>
                    </ul>

                    <h2 className="text-xl font-semibold mt-6 mb-3">2. Disclaimer &amp; Liability</h2>
                    <p>We do not guarantee the accuracy, timeliness, or completeness of information provided on the Platform. Your use of the Services is at your sole risk. We will not be liable for indirect, incidental, or consequential damages, including business losses.</p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">3. Intellectual Property</h2>
                    <p>All designs, text, graphics, and content on the Platform are the property of Reused.in. You may not reproduce, copy, or exploit them without prior written consent.</p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">4. Payments &amp; Transactions</h2>
                    <p>By initiating a purchase or transaction, you enter into a legally binding contract with Reused.in. You agree to pay the applicable charges.</p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">5. Restrictions</h2>
                    <p className="mb-2">You must not use the Platform to:</p>
                    <ul className="list-disc ml-6 mb-4 space-y-1">
                        <li>Engage in unlawful or prohibited activities.</li>
                        <li>Upload harmful or infringing content.</li>
                        <li>Violate intellectual property rights of third parties.</li>
                    </ul>

                    <h2 className="text-xl font-semibold mt-6 mb-3">6. Indemnity</h2>
                    <p>You agree to indemnify and hold harmless Reused.in, its directors, employees, and affiliates from any claims or damages arising from your breach of these Terms.</p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">7. Force Majeure</h2>
                    <p>We are not liable for delays or failure caused by events outside our control, including natural calamities, system failures, or government actions.</p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">8. Governing Law &amp; Jurisdiction</h2>
                    <p>These Terms are governed by the laws of India. All disputes will be subject to the exclusive jurisdiction of the courts in Karnataka, India.</p>

                    <h2 className="text-xl font-semibold mt-6 mb-3">9. Contact Us</h2>
                    <p>If you have questions about these terms, contact us:</p>
                    <p className="mt-2">
                        <strong>Email:</strong> <a href="mailto:support@reused.in" className="text-blue-600 hover:underline">support@reused.in</a><br />
                        <strong>Address:</strong> 680/58, 30th Cross, Swagat Road, 4th T Block East, Jayanagar, Bengaluru, Karnataka 560041
                    </p>
                </div>
            </main>
            <Footer />
        </>
    );
}
